### ISSUE TITLE
Threshold problem

### ISSUE THREAD

**Issue by KhaledElAnsari** [benmajor/jQuery-Touch-Events#66]
Hello..

I'm using this library for my phonegap app and I tried to change the threshold of the horizontal swipe for my swipeleft & swiperight but it didn't work! any idea why?

Note: I tried this attribute ( data-xthreshold="500" ) also tried the vertical one and nothing change for the swipeup & swipedown

**Comment by benmajor** [comment]
Thanks for your message. Would you please be able to set up a jsFiddle or something similar to replicate the problem?

**Comment by KhaledElAnsari** [comment]
my code is not complicated I added the threshold attribute to the swipe dive like this 

<div id="homePage" data-xthreshold="200" data-ythreshold="100">

and my js for the swipe is like this

$('#homePage').on('swipeleft',function(e){ 
 // my code goes here
});

that's it.

**Comment by benmajor** [comment]
I'm afraid that the problem must be elsewhere in your code. For example, I have set up a demo showing the same code you indicated (except I changed the `data-xthreshold` to `500`):

http://ben-major.com/events-test/

As you can see, the JS `alert` is correctly triggered when swiping left has occurred for `501` pixels. Did you make sure that you wrapped the event binding inside of the `DOMReady` event? The JS code used in the demo URL is:

    $(function() {        
        $('#homePage').on('swipeleft',function(e, touch) { 
            alert(touch.xAmount);
        });
    });

I will close this request, because the problem cannot be replicated.

**Comment by EloB** [comment]
How should the threshold suppose to work? If you attach swipe event on a element should you have to attach threshold to all the child elements?

http://jsfiddle.net/66sxrk6u/3/

**Comment by benmajor** [comment]
Thanks for the heads-up EloB.

There was a bug where the threshold of a `swipe` event would be ignored if the actual `move` event occurred on the element's children. This was fixed by checking for a `threshold` parameter on the parent element during the move event. This has now been resolved as part of the following push: 

https://github.com/benmajor/jQuery-Touch-Events/commit/a7707dd3591379133772fa53c719bced133f7713

You can see the expected behaviour is now present here >  http://jsfiddle.net/66sxrk6u/5/

**Comment by EloB** [comment]
Still not working. You should probably use currentTarget instead of target.

http://jsfiddle.net/66sxrk6u/6/

**Comment by benmajor** [comment]
Thanks, @EloB. Using `currentTarget` seems to have resolved the problem, and should be fixed in the latest push. https://github.com/benmajor/jQuery-Touch-Events/commit/fb25a12c804ad9aef1f5f1dfa772d9eafb33b087

Please see here > http://jsfiddle.net/66sxrk6u/7/

**Comment by EloB** [comment]
:+1:
